### PR TITLE
Add a rewrite rule to repair the LDAP/AD app

### PR DESCRIPTION
**Pull request by lbarnett83**
This line will repair an issue wherein the LDAP app within NextCloud will not function with this container.

I added this line within my own container for testing purposes, and it resolved the LDAP app issue.
 Closes issue #195

### CODE REVIEW

**Comment by ibracorp** [comment]
Please guys make this happen! The community is keen

**Comment by llasse** [comment]
I also added this line, restartet nginx inside the container via `nginx -s reload -c /config/nginx/nginx.conf` but I still cannot proceed from the ldap plugin config page..

**Comment by ABotelho23** [comment]
Has there been any movement for this? LDAP is a pretty critical/core feature.

**Comment by aptalca** [comment]
It needs to be fixed upstream first

**Comment by lbarnett83** [comment]
Any thoughts/notes on this PR?

**Comment by wolflarson** [comment]
Is anyone aware of a fork that has this workaround in place that we can switch to until upstream fixes this issue? occ ldap:show-config has its limitations ...

**Comment by ABotelho23** [comment]
I'm not actually sure what the issue here. Is this not an NGINX conf fix? Why do we need to wait for upstream (assuming the Nextcloud the server software) to repair this?
It's very odd to me that a critical feature like LDAP could remain broken for so long. How do people even use Nextcloud for more than handful of people without LDAP?

**Comment by aptalca** [comment]
> Why do we need to wait for upstream (assuming the Nextcloud the server software) to repair this?

Because the proposed fix may break something else and put us in a whack a mole situation we have no interest in being. We follow the upstream recommended nginx config almost 1:1. The actual `fix` needs to be fully tested and applied to upstream, then we'll update ours.

In the meantime, any user can easily modify their config as the nginx confs are all user configurable and they reside in the config folder.

**Comment by wolflarson** [comment]
https://github.com/nextcloud/server/issues/27871 here i the upstream issue.

**Review by Sblop — APPROVED** [review]
I confirm this works!

**Comment by drizuid** [comment]
closing this, work-around is provided in this thread and we will not fix at our level.

**Pull request closed without merging**
