### PR TITLE
Dockerfile: Raise opcache interned strings buffer to 16

### LINKED ISSUE #235: PHP OPcache module is not properly configured: OPcache interned strings buffer is nearly full
Using docker for (Unraid) (Linux x64)
The issue is opened in official nextcloud:
https://github.com/nextcloud/docker/issues/1692

### PR DESCRIPTION
**Pull request by axelsimon**
In line with https://github.com/nextcloud/docker/pull/1702/ and to avoid the error message:
> The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.

--- 

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-nextcloud/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

## Description:
Raise OPCache interned strings buffer to 16 instead of 8.

## Benefits of this PR and context:
Removes the error message.

## How Has This Been Tested?
Tested on a live container to work and remove the error message.

## Source / References:
https://github.com/nextcloud/server/issues/31223

closes #235

### CODE REVIEW

**Comment by TheSpad** [comment]
Please add a changelog entry to the readme-vars.yml

**Comment by axelsimon** [comment]
@TheSpad Done :)

**Review by TheSpad — APPROVED** [review]
LGTM

**Comment by masterwishx** [comment]
i have this message after update to 23.0.4

**Pull request merged**
