### PR TITLE
Add imagemagick support for dynamic icon generation.

### PR DESCRIPTION
**Pull request by tomtom5152**
Install the additional packages required to support [theme icon generation](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/theming.html#theming-of-icons).

### CODE REVIEW

**Comment by tomtom5152** [comment]
Just realised I accidentally deleted the repo for this whilst attempting to create my own image having forgotten that I did this 9 days ago after running docker pull on my server. I'm an idiot. Let me know if the PR merge has an issues as a result, I can recreate it very quickly.

**Comment by Skydiver84de** [comment]
Hi,
I suggest to approve this PR as it is working without any problems and is a good improvement.

BR

**Comment by tomtom5152** [comment]
Bump, any chance of some movement on this?

**Comment by alex-phillips** [comment]
@tomtom5152 This looks good to me. If you can add this / create the PR on the other versions, I'll approve and merge all 3.

**Pull request merged**
