### PR TITLE
Manually install iconv as the one provided in Alpine does not work

### LINKED ISSUE #165: Nextcloud Mail broken, messages not loading (Nextcloud 20.0.1/Mail 1.5.1)
## Expected Behavior
When opening Mail app in NC, new mails are shown. This seems to be a known problem mit Alpine-based Docker images: https://github.com/nextcloud/mail/issues/3908

## Current Behavior
No mails shown, stuck loading

## Steps to Reproduce
1. Update to latest version of Nextcloud and Mail
2. Open Mail app (with Mail account set up)

## Environment
**OS:** Openmediavault/Debian Buster
**CPU architecture:** x86_64
**How docker service was installed:** Official Repo

Below the log entry from my instance when opening Mail

[PHP] Error: Error: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed at /config/www/nextcloud/apps/mail/lib/Address.php#70 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8, "iconv(): Wrong  ... d", "/config/www/nex ... p", 70, [])
 1. /config/www/nextcloud/apps/mail/lib/Address.php line 70
    iconv("UTF-8", "UTF-8//IGNORE", "*****.********@gmail.com")
 2. /config/www/nextcloud/apps/mail/lib/Address.php line 86
    OCA\Mail\Address->getEmail()
 3. /config/www/nextcloud/apps/mail/lib/AddressList.php line 100
    OCA\Mail\Address->jsonSerialize()
 4. <<closure>>
    OCA\Mail\AddressList->OCA\Mail\{closure}("*** sensitive parameters replaced ***")
 5. /config/www/nextcloud/apps/mail/lib/AddressList.php line 101
    array_map(Closure {}, ["*** sensitive parameter replaced ***"])
 6. /config/www/nextcloud/apps/mail/lib/Db/Message.php line 254
    OCA\Mail\AddressList->jsonSerialize()
 7. <<closure>>
    OCA\Mail\Db\Message->jsonSerialize()
 8. /config/www/nextcloud/lib/public/AppFramework/Http/JSONResponse.php line 73
    json_encode([OCA\Mail\Db\Mes ... }], 1)
 9. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 123
    OCP\AppFramework\Http\JSONResponse->render()
10. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\MessagesController {}, "index")
11. /config/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "index", OC\AppFramework\ ... {}, {action: null,_r ... "})
12. /config/www/nextcloud/lib/base.php line 1009
    OC\Route\Router->match("/apps/mail/api/messages")
13. /config/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /apps/mail/api/messages?mailboxId=95&limit=20
from 193.222.*.* by **** at 2020-11-03T14:50:21+00:00

### PR DESCRIPTION
**Pull request by tfmm**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-nextcloud/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This manually installs the PHP iconv extension, as the one provided in Alpine repositories does not work correctly. 

## Benefits of this PR and context:

As Mentioned in #165 iconv on alpine is not working properly, causing an issue for some extensions and NC functionality. 

Closes #165 

## How Has This Been Tested?

Built all 3 images without issue. 
Ran the standard image without issue. 
Reviewed NC functionality across multiple portions of the application, no issues found.

## Source / References:

Ref: https://github.com/docker-library/php/issues/240#issuecomment-373723043
Ref: https://github.com/linuxserver/docker-nextcloud/issues/165
Ref: https://github.com/nextcloud/mail/issues/3999
Ref: https://github.com/nextcloud/mail/issues/3908

### CODE REVIEW

**Comment by aptalca** [comment]
I really think it would be much simpler to PR a fix to the alpine repo package rather than compiling here and setting php versions manually

**Comment by tfmm** [comment]
While I do not disagree, from multiple references around the internet, the Alpine maintainers do not appear to be willing to fix the issue on their end.

**Comment by aptalca** [comment]
We've actually fixed quite a few upstream bugs there via PRs. Their maintainers may not be super proactive but they are very much open to community PRs.

With that said, I've been on mobile and have not looked into what the upstream issue is.

**Comment by tfmm** [comment]
Still testing, but I may have found a cleaner way to handle this, will update the PR or close it and open a new one if the testing works out.

**Comment by tfmm** [comment]
Updated the PR as there is a work-around that only involves installing gnu-libiconv from community repos and not having to manually compile.

**Comment by stavros-k** [comment]
I fixed it with the following script. There might be easier way out there. But this script i found somewhere (i dont really remember sorry) fixed it.

```
PHP_VER=$(php -v | grep ^PHP | cut -d' ' -f2) && \
BUILD_PACKAGES="wget build-base php7-dev" && \

apk add --no-cache --virtual .php-build-dependencies $BUILD_PACKAGES && \
apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ gnu-libiconv-dev && \
(mv /usr/bin/gnu-iconv /usr/bin/iconv; mv /usr/include/gnu-libiconv/*.h /usr/include; rm -rf /usr/include/gnu-libiconv) && \
mkdir -p /opt && \
cd /opt && \
wget https://secure.php.net/distributions/php-$PHP_VER.tar.gz && \
tar xzf php-$PHP_VER.tar.gz && \
cd php-$PHP_VER/ext/iconv && \
phpize && \
./configure --with-iconv=/usr && \
make && \
make install && \
mkdir -p /etc/php7/conf.d && \
#next command not needed in LSIO Docker
#echo "extension=iconv.so" >> /etc/php7/conf.d/iconv.ini && \

apk del .php-build-dependencies && \
rm -rf /opt/*
```

**Comment by tobbenb** [comment]
> Updated the PR as there is a work-around that only involves installing gnu-libiconv from community repos and not having to manually compile.

There was a user on the unraid forum I asked to install the gnu-libiconv package, but it didn't fix the issue. php7-iconv is installed when we build the container if I'm not mistaken.

**Comment by tfmm** [comment]
I found the same thing when I installed gnu-libiconv after the container was built. However, I found that if I installed it during build, and then installed php7-iconv afterwards, and also from the community repo vs the main repo, it worked. I also set the LD_PRELOAD env variable to load the extension.

**Comment by DataHearth** [comment]
Hello there, is this PR will be merged soon ? I'm really looking forward to get rid of my custom image on my unRAID server.
That could be a cool a update for unRAID users. That would avoid doing a custom image based on this one with the fix 👌.

**Comment by Manu3l0us** [comment]
Any chance to get this merged?

**Comment by aptalca** [comment]
This is too hacky for my taste, as the main and edge repos provide different versions of php. This really should be fixed upstream as I suggested before. Did you submit a PR there or open an issue?

**Comment by ageisen2000** [comment]
@aptalca https://github.com/docker-library/php/issues/240#issuecomment-353678474

is this the correct spot to look for? if so, this maintainer doesn't seem to want to change the functionality?

**Comment by aptalca** [comment]
Correct spot is the alpine gitlab repo: https://gitlab.alpinelinux.org/alpine/aports

**Comment by itsthejb** [comment]
YMMV, whilst I'm a huge fan of Linux server images, decided to move over to the official Debian image for this one. Seems nextcloud is getting a bit huge and feature rich these days, and the alpine base might not be enough going forward (just my 10c)

**Comment by Manu3l0us** [comment]
@itsthejb 
I'm considering this step too. Still a bit worried about the migration though, is there a guide or do you have written down the process by any chance?

**Comment by aptalca** [comment]
A lot of folks complaining in this thread about alpine, yet not a single person even attempted to submit a patch upstream. It shouldn't be that hard as the edge version works, but not the 3.12 version. Looking at the build differences would likely easily reveal the necessary fix.

**Comment by ageisen2000** [comment]
Now that I know where to look I will try to see if I can look at submitting a pr, but with the holidays and my very tiny amount of knowledge around alpine it'll be difficult.

I agree that an upstream fix seems a lot better. Thanks for pointing out where the repo was for me!

**Comment by HannesJo0139** [comment]
So for now, simply switching to your image should work, right? It is because I tried that and still the iconv error occurs.

**Comment by Intenos** [comment]
Has this fix already been requested from the Alpine developers? I´m also interested in having it working.

**Comment by aptalca** [comment]
Well, if no one does anything, the version on edge will end up on alpine 3.13 any day now

**Comment by Intenos** [comment]
I have not added a request on Github yet. What would I need to exactly ask for? Is it sufficient to add an issue named "Please add/fix iconv extension" and link also to this issue here?

**Comment by Poltergeisen** [comment]
@aptalca when you say any day now do you think within the next week or two? That might be faster than I can get to the PR anyways

**Comment by aptalca** [comment]
Could be: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Pull request closed without merging**
