### PR TITLE
Change the default header of X-Robots-Tag to "noindex, nofollow"

### LINKED ISSUE #298: Header Error + Php Module After Update to v26.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Unraid Docker lasted version.
After Updated to Nextcloud v 26.0 ,got 2 errors :
1. header missing HTTP «X-Robots-Tag» not setup to  «noindex, nofollow». 
2. Php module not installed sysvsem

image

### Expected Behavior

was no errors on previos version

### Steps To Reproduce

..

### Environment

```markdown
Unraid (Linux x64)
```

### CPU architecture

x86-64

### Docker creation

```bash
..
```

### Container logs

```bash
..
```

### PR DESCRIPTION
**Pull request by stavros-k**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-nextcloud/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

NC 26 shows the bellow warning:

image

## Benefits of this PR and context:

Partially fixes #298 

Follow upstream nextcloud suggestions

## How Has This Been Tested?

Manually made the changes on my instance, restarted it and warning was gone.
Also checked headers in the dev tools in browser

### CODE REVIEW

**Comment by thespad** [comment]
The X-Robots-Tag header [is set](https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/nginx/site-confs/default.conf.sample#L54) to `none`, this is equivalent to `noindex, nofollow` [source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#other_metadata_names), so I have no idea why Nextcloud have decided to pointless change their detection for this.

**Comment by aptalca** [comment]
Pretty sure when it comes to header detection, Nextcloud looks for an exact match of whatever parameter they like, and if it doesn't match exactly, it complains.

**Comment by thespad** [comment]
Yeah, but in previous versions they were happy with `none`, because that's what we've used for ages, which suggests they've changed what they're looking for.

**Comment by stavros-k** [comment]
https://github.com/nextcloud/server/pull/36689

```
While "none" is indeed equivalent to "noindex, nofollow" for Google, but seems to be not supported by Bing and probably other search engines.
```

**Review by thespad — APPROVED** [review]

**Pull request merged**
