### PR TITLE
update default site config for v21

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

**Comment by stavros-k** [comment]
Deteled `/config/nginx/site-confs/default` updated container. (default recreated)
But i still get `Your web server is not properly set up to resolve "/.well-known/webfinger"`

**Comment by j0nnymoe** [comment]
@stavros-k please open a new issue rather than commenting on a closed PR. This works as it's been tested by a couple of us internally that are running v21.

**Comment by HannesJo0139** [comment]
@stavros-k have you updated the docker image?

**Comment by stavros-k** [comment]
> @stavros-k have you updated the docker image?

As I mentioned, yes I did updated the container and deleted the default, and it got recreated

**Comment by HannesJo0139** [comment]
Ah missed that, sorry. I needed to delete defaults file again after container update. For some reason it downloaded the old version at first try.

**Pull request merged**
