### PR TITLE
Modify www.conf for tuning php-fpm

### PR DESCRIPTION
**Pull request by bulzipke**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Benefits of this PR and context:

By default, the php-fpm setting is too small for the value recommended by the Nextcloud documentation. So I made the modifications so that I could set the value recommended in the document.

## Source / References:

https://docs.nextcloud.com/server/17/admin_manual/installation/server_tuning.html#tune-php-fpm

### CODE REVIEW

**Comment by tobbenb** [comment]
Please fill in the information we ask about or we'll close the PR.

**Comment by bulzipke** [comment]
> Please fill in the information we ask about or we'll close the PR.

Ah, I did

**Comment by aptalca** [comment]
Are these values common denominators for all devices we support including an arm device with 1gb of ram? They don't seem so.

www.conf is already user configurable via /config/php/www2.conf
Any device/user specific values should be entered in there manually

**Comment by bulzipke** [comment]
> Are these values common denominators for all devices we support including an arm device with 1gb of ram? They don't seem so.
> 
> [www.conf](http://www.conf) is already user configurable via /config/php/www2.conf
> Any device/user specific values should be entered in there manually

Ah, I see. Thank you for your explanation. I'll close the issue.

**Pull request closed without merging**
