### PR TITLE
fixed diffs w/ upstream nextcloud git

### PR DESCRIPTION
**Pull request by FiddlyRumpus**
Edit line 53, 67 - ocs-provider + ocm-provider, one call:
https://github.com/nextcloud/documentation/commit/3206db9fb8290343753828b10f817cf066cf88bd
https://github.com/nextcloud/documentation/pull/1293

New line 55, edit 58 - try_files resets $fastcgi_path_info, fix so $path_info gets value:  
https://github.com/nextcloud/documentation/commit/8f6c1aa61aa3cd9d9e3e567c0afe4a822d3fc403
https://github.com/nextcloud/documentation/pull/1679

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

### CODE REVIEW

**Comment by aptalca** [comment]
@FiddlyRumpus can you rebase and PR against branch v18? We're collecting various optimizations there before merge. Thanks

**Comment by FiddlyRumpus** [comment]
rebased against v18 @aptalca

**Comment by aptalca** [comment]
You need to rebase and prevent all conflicts. Feel free to open a fresh PR

**Comment by FiddlyRumpus** [comment]
Conflict resolved @aptalca

**Pull request merged**
